number1 = int(10)
number2 = int(11)
number3 = int(12)
number4 = int(13)

print('add =')
print(number1+number2+number3+number4)
print ('mult =')
print(number1*number2*number3*number4)
print ('subtract =')
print(number4-number3-number2-number1)
print ('division =')
print(number4/number3)

number1 = int(13)
number2 = int(12)
number3 = int(11)
number4 = int(10)

print('add =')
print(number1+number2)
print ('mult =')
print(number3*number4)
print ('subtract =')
print(number1-number2)
print ('division =')
print(number1/number2)